apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
  labels:
    app: second-app-dp
spec:
  template:
    metadata:
      labels:
        app: second-app
    spec:
      containers:
      - name: second-app-container
        image: asinha37/kube-first-app:latest
        ports:
        - containerPort: 8080
  replicas: 4
  selector:
    matchLabels:
      app: second-app
