apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
  labels:
    app: tasks-api-dpl
spec:
  template:
    metadata:
      labels:
        app: tasks-api
    spec:
      containers:
        - name: tasks-api-container
          image: asinha37/tasks-api:latest
          env:
            - name: AUTH_ADDRESS
              value: auth-service.default
            - name: TASKS_FOLDER
              value: tasks
          ports:
            - containerPort: 8000
  replicas: 1
  selector:
    matchLabels:
      app: tasks-api
