apiVersion: v1
kind: ReplicationController
metadata:
  name: my-busy-box-replication-controller
  labels:
    app: my-busy-box--front-end-app
    type: busy-box-front-end-app
spec:
  template:
    metadata:
      name: busybox
      labels:
        app: busy-box-pod
        type: busy-box-pod
    spec:
      containers:
        - image: nginx
          name: my-busybox-container
  replicas: 4
