apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replica-set
  labels:
    app : my-repica-set-app
    tier: front-end-application
spec:
  template:
    metadata:
      labels: 
        type: front-end-app
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 6
  selector: 
    matchLabels:
      type : front-end-app