apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replica-set
  labels:
    name: my-app
    type: front-end-app
spec:
  template:
    metadata:
      labels:
        name: nginx-front-end-app
    spec:
      containers:
        - name: nginx
          image: nginx
  replicas: 3
  selector:
    matchLabels:
      name: nginx-front-end-app